on: [push, pull_request]
name: Tests
jobs:
  build:
    name: TestsInBuild
    runs-on: 	ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.20.3'
    - run: flutter channel dev
    - run: flutter upgrade
    - run: flutter pub get
    - run: flutter test || true
    - run: base64 /home/runner/work/forest_venture/forest_venture/test/failures/basic_world_1_masterImage.png
